### ISSUE TITLE
Tests failing occasionally

### ISSUE THREAD

**Issue by michaltakac** [varunjayaraman/braintree-node#1]
These tests are sometimes failing:
1. can find a customer
2. can update a customer
3. can clone a transaction

first two with error:
`Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

third:
```
AssertionError: false == true
      + expected - actual

      -false
      +true

      at test.js:99:14
      at next (native)
      at onFulfilled (node_modules/co/index.js:65:19)
```

Ran tests 10 times, first two failed 5 times, third failed 7 times.

Btw nice work, will help with adding methods for subscriptions.

**Comment by varunjayaraman** [comment]
Thanks, it's an issue with the timeout - mocha defaults to a timeout of 2000ms. Problem is, the time it takes to hit braintree's servers and come back probably exceeds that. I'll probably need to stub out the braintree functions, but the functionality should still work (I use the library at my company).

**Comment by varunjayaraman** [comment]
Also @michaltakac appreciate the help. Haven't really used subscriptions yet, so any help on that front would be a huge assistance

**Comment by michaltakac** [comment]
I've been wrapping my gateway.subscription.* methods in Promises so considered it would be helpful to add them to this package and then use it in my projects, others would also benefit from it I guess :)

**Comment by varunjayaraman** [comment]
Sorry about letting this repo go. I'll try to stub out some of these braintree methods so the tests dont timeout occasionally + I'll try to maintain this better.
